---

- name: Check if PostgreSQL database is initialized.
  stat:
    path: "{{ postgresql_cluster_data_dir }}/PG_VERSION"
  register: pgdata_dir_version

- name: "copy deb.sh to /tmp/pg_auto_failover_deb.sh"
  copy:
    src: "deb.sh"
    dest: "/tmp/pg_auto_failover_deb.sh"
    owner: root
    group: root
    mode: 0700
  when: not pgdata_dir_version.stat.exists

- name: "run /tmp/pg_auto_failover_deb.sh"
  command: "bash /tmp/pg_auto_failover_deb.sh"
  when: not pgdata_dir_version.stat.exists

# Not needed in newer versions, is bad, because installs pg-11 too
# - name: "install pg-auto-failover-cli"
#   apt:
#     name: "pg-auto-failover-cli"
#     state: present
#     update_cache: "{{ apt_update_cache | default('True') }}"
#   when: not pgdata_dir_version.stat.exists

- name: "install postgresql-{{ postgresql_cluster_version }}-auto-failover"
  apt:
    name: "postgresql-{{ postgresql_cluster_version }}-auto-failover"
    state: present
    update_cache: "{{ apt_update_cache | default('True') }}"
  when: not pgdata_dir_version.stat.exists
